/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author LABCISCO-PC059
 */
public class JframeEstudianteElegirPC extends javax.swing.JFrame {

    private int PCAux = 0; //int que indica la PC seleccionada.
    private int HorasAux = 0; //int que indica cuantas hora se ocupara la PC.

    /**
     * Creates new form JframeElegirSoftware
     */
    public JframeEstudianteElegirPC() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabelPC1 = new javax.swing.JLabel();
        jLabelNumero1 = new javax.swing.JLabel();
        jLabelPCElegida = new javax.swing.JLabel();
        jLabelPC2 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jLabelPC3 = new javax.swing.JLabel();
        jLabelNumero3 = new javax.swing.JLabel();
        jLabelPC4 = new javax.swing.JLabel();
        jLabelNumero4 = new javax.swing.JLabel();
        jLabelPC5 = new javax.swing.JLabel();
        jLabelNumero5 = new javax.swing.JLabel();
        jLabelPC6 = new javax.swing.JLabel();
        jLabelNumero6 = new javax.swing.JLabel();
        jLabelPC7 = new javax.swing.JLabel();
        jLabelNumero7 = new javax.swing.JLabel();
        jLabelPC8 = new javax.swing.JLabel();
        jLabelNumero8 = new javax.swing.JLabel();
        jLabelPC9 = new javax.swing.JLabel();
        jLabelNumero9 = new javax.swing.JLabel();
        jLabelPC10 = new javax.swing.JLabel();
        jLabelNumero10 = new javax.swing.JLabel();
        jLabelPC11 = new javax.swing.JLabel();
        jLabelNumero11 = new javax.swing.JLabel();
        jLabelPC12 = new javax.swing.JLabel();
        jLabelNumero12 = new javax.swing.JLabel();
        jLabelPC13 = new javax.swing.JLabel();
        jLabelNumero13 = new javax.swing.JLabel();
        jLabelPC14 = new javax.swing.JLabel();
        jLabelNumero14 = new javax.swing.JLabel();
        jLabelPC15 = new javax.swing.JLabel();
        jLabelNumero15 = new javax.swing.JLabel();
        jLabelPC16 = new javax.swing.JLabel();
        jLabelNumero16 = new javax.swing.JLabel();
        jLabelPC17 = new javax.swing.JLabel();
        jLabelNumero17 = new javax.swing.JLabel();
        jLabelPC18 = new javax.swing.JLabel();
        jLabelNumero18 = new javax.swing.JLabel();
        jLabelPC19 = new javax.swing.JLabel();
        jLabelNumero19 = new javax.swing.JLabel();
        jLabelPC20 = new javax.swing.JLabel();
        jLabelNumero20 = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jLabelHoras = new javax.swing.JLabel();
        jLabelPC = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCentroComputo = new javax.swing.JLabel();
        jLabelNombreAlumno = new javax.swing.JLabel();
        jLabelCarrera = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelLogoItson = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 600));

        jPanelFondo.setBackground(new java.awt.Color(153, 204, 255));

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabelPC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC1MouseClicked(evt);
            }
        });

        jLabelNumero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero1.setText("1");

        jLabelPCElegida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPCElegida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelPC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC2MouseClicked(evt);
            }
        });

        jLabelNumero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero2.setText("2");

        jLabelPC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC3MouseClicked(evt);
            }
        });

        jLabelNumero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero3.setText("3");

        jLabelPC4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC4MouseClicked(evt);
            }
        });

        jLabelNumero4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero4.setText("4");

        jLabelPC5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC5MouseClicked(evt);
            }
        });

        jLabelNumero5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero5.setText("5");

        jLabelPC6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC6MouseClicked(evt);
            }
        });

        jLabelNumero6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero6.setText("6");

        jLabelPC7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC7MouseClicked(evt);
            }
        });

        jLabelNumero7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero7.setText("7");

        jLabelPC8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC8MouseClicked(evt);
            }
        });

        jLabelNumero8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero8.setText("8");

        jLabelPC9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC9MouseClicked(evt);
            }
        });

        jLabelNumero9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero9.setText("9");

        jLabelPC10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC10MouseClicked(evt);
            }
        });

        jLabelNumero10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero10.setText("10");

        jLabelPC11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC11MouseClicked(evt);
            }
        });

        jLabelNumero11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero11.setText("11");

        jLabelPC12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC12MouseClicked(evt);
            }
        });

        jLabelNumero12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero12.setText("12");

        jLabelPC13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC13MouseClicked(evt);
            }
        });

        jLabelNumero13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero13.setText("13");

        jLabelPC14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC14MouseClicked(evt);
            }
        });

        jLabelNumero14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero14.setText("14");

        jLabelPC15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC15MouseClicked(evt);
            }
        });

        jLabelNumero15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero15.setText("15");

        jLabelPC16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC16MouseClicked(evt);
            }
        });

        jLabelNumero16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero16.setText("16");

        jLabelPC17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC17MouseClicked(evt);
            }
        });

        jLabelNumero17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero17.setText("17");

        jLabelPC18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC18MouseClicked(evt);
            }
        });

        jLabelNumero18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero18.setText("18");

        jLabelPC19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC19MouseClicked(evt);
            }
        });

        jLabelNumero19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero19.setText("19");

        jLabelPC20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PC (1).png"))); // NOI18N
        jLabelPC20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPC20MouseClicked(evt);
            }
        });

        jLabelNumero20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero20.setText("20");

        jTextFieldHoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldHorasFocusLost(evt);
            }
        });
        jTextFieldHoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldHorasMouseExited(evt);
            }
        });
        jTextFieldHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorasActionPerformed(evt);
            }
        });

        jLabelHoras.setBackground(new java.awt.Color(0, 0, 0));
        jLabelHoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHoras.setText("Horas");

        jLabelPC.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPC.setText("PC:");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Instituto Tecnologico de Sonora");

        jLabelCentroComputo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCentroComputo.setText("Nombre de Centro: ");

        jLabelNombreAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreAlumno.setText("Nombre de Alumno:");

        jLabelCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarrera.setText("Carrera:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabelLogoItson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoItson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LogoITSON.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addComponent(jLabelLogoItson, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabelCentroComputo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPCElegida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabelPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabelNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabelPC8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPC14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPC15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPC16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPC17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPC18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPC19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPC20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabelNumero15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelNumero20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogoItson, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelCentroComputo))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelPC)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPCElegida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPC1)
                    .addComponent(jLabelPC2)
                    .addComponent(jLabelPC3)
                    .addComponent(jLabelPC4)
                    .addComponent(jLabelPC5)
                    .addComponent(jLabelPC6)
                    .addComponent(jLabelPC7))
                .addGap(10, 10, 10)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHoras)
                    .addComponent(jLabelNumero1)
                    .addComponent(jLabelNumero2)
                    .addComponent(jLabelNumero3)
                    .addComponent(jLabelNumero4)
                    .addComponent(jLabelNumero5)
                    .addComponent(jLabelNumero6)
                    .addComponent(jLabelNumero7))
                .addGap(4, 4, 4)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPC8)
                    .addComponent(jLabelPC9)
                    .addComponent(jLabelPC10)
                    .addComponent(jLabelPC11)
                    .addComponent(jLabelPC12)
                    .addComponent(jLabelPC13)
                    .addComponent(jLabelPC14))
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonVolver))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNumero8)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPC15))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNumero9)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPC16))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNumero10)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPC17))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNumero11)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPC18))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNumero12)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPC19))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelNumero13)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPC20))
                    .addComponent(jLabelNumero14))
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero15)
                    .addComponent(jLabelNumero16)
                    .addComponent(jLabelNumero17)
                    .addComponent(jLabelNumero18)
                    .addComponent(jLabelNumero19)
                    .addComponent(jLabelNumero20)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPC8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC8MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero8.getText()); //Se muestra la PC elegida en pantalla.
        PCAux = 8; //Se guarda la PC Elegida para su posterior uso.
    }//GEN-LAST:event_jLabelPC8MouseClicked

    private void jLabelPC7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC7MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero7.getText()); //Se muestra la PC elegida en pantalla.
        PCAux = 7; //Se guarda la PC Elegida para su posterior uso.
    }//GEN-LAST:event_jLabelPC7MouseClicked

    private void jLabelPC6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC6MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero6.getText()); //Se muestra la PC elegida en pantalla.
        PCAux = 6; //Se guarda la PC Elegida para su posterior uso.
    }//GEN-LAST:event_jLabelPC6MouseClicked

    private void jLabelPC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC5MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero5.getText()); //Se muestra la PC elegida en pantalla.
        PCAux = 5; //Se guarda la PC Elegida para su posterior uso.
    }//GEN-LAST:event_jLabelPC5MouseClicked

    private void jLabelPC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC4MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero4.getText()); //Se muestra la PC elegida en pantalla.
        PCAux = 4; //Se guarda la PC Elegida para su posterior uso.
    }//GEN-LAST:event_jLabelPC4MouseClicked

    private void jLabelPC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC3MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero3.getText()); //Se muestra la PC elegida en pantalla.
        PCAux = 3; //Se guarda la PC Elegida para su posterior uso.
    }//GEN-LAST:event_jLabelPC3MouseClicked

    private void jLabelPC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC2MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero2.getText()); //Se muestra la PC elegida en pantalla.
        PCAux = 2; //Se guarda la PC Elegida para su posterior uso.
    }//GEN-LAST:event_jLabelPC2MouseClicked

    private void jLabelPC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC1MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero1.getText());
        PCAux = 1;
    }//GEN-LAST:event_jLabelPC1MouseClicked

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        //Validacion de horas
        try {
            int aux = Integer.parseInt(this.jTextFieldHoras.getText());
            if (aux <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Horas no puede ser 0");
            } else {
                HorasAux = aux;
            }

            //Validacion de PC.
            if (PCAux <= 0 || HorasAux <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Debe elegir una pc y introducir cuanto tiempo la utilizara");
            } else {
                PCAux = Integer.parseInt(this.jLabelPCElegida.getText());
                System.out.println(PCAux);
                System.out.println(HorasAux);
                JframeEstudiantePCApartada j = new JframeEstudiantePCApartada(PCAux, HorasAux); //Se ingresan la pc y las horas.
                j.setVisible(true);
                this.dispose();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Valores no validos");
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        JframeEstudianteIngreso j = new JframeEstudianteIngreso();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jLabelPC9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC9MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero9.getText());
        PCAux = 9;
    }//GEN-LAST:event_jLabelPC9MouseClicked

    private void jLabelPC10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC10MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero10.getText());
        PCAux = 10;
    }//GEN-LAST:event_jLabelPC10MouseClicked

    private void jLabelPC11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC11MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero11.getText());
        PCAux = 11;
    }//GEN-LAST:event_jLabelPC11MouseClicked

    private void jLabelPC12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC12MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero12.getText());
        PCAux = 12;
    }//GEN-LAST:event_jLabelPC12MouseClicked

    private void jLabelPC13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC13MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero13.getText());
        PCAux = 13;
    }//GEN-LAST:event_jLabelPC13MouseClicked

    private void jLabelPC14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC14MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero14.getText());
        PCAux = 14;
    }//GEN-LAST:event_jLabelPC14MouseClicked

    private void jLabelPC15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC15MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero15.getText());
        PCAux = 15;
    }//GEN-LAST:event_jLabelPC15MouseClicked

    private void jLabelPC16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC16MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero16.getText());
        PCAux = 16;
    }//GEN-LAST:event_jLabelPC16MouseClicked

    private void jLabelPC17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC17MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero17.getText());
        PCAux = 17;
    }//GEN-LAST:event_jLabelPC17MouseClicked

    private void jLabelPC18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC18MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero18.getText());
        PCAux = 18;
    }//GEN-LAST:event_jLabelPC18MouseClicked

    private void jLabelPC19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC19MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero19.getText());
        PCAux = 19;
    }//GEN-LAST:event_jLabelPC19MouseClicked

    private void jLabelPC20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPC20MouseClicked
        this.jLabelPCElegida.setText(this.jLabelNumero20.getText());
        PCAux = 20;
    }//GEN-LAST:event_jLabelPC20MouseClicked

    private void jTextFieldHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorasActionPerformed

    private void jTextFieldHorasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHorasFocusLost

    }//GEN-LAST:event_jTextFieldHorasFocusLost

    private void jTextFieldHorasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHorasMouseExited

    }//GEN-LAST:event_jTextFieldHorasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelCarrera;
    private javax.swing.JLabel jLabelCentroComputo;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelLogoItson;
    private javax.swing.JLabel jLabelNombreAlumno;
    private javax.swing.JLabel jLabelNumero1;
    private javax.swing.JLabel jLabelNumero10;
    private javax.swing.JLabel jLabelNumero11;
    private javax.swing.JLabel jLabelNumero12;
    private javax.swing.JLabel jLabelNumero13;
    private javax.swing.JLabel jLabelNumero14;
    private javax.swing.JLabel jLabelNumero15;
    private javax.swing.JLabel jLabelNumero16;
    private javax.swing.JLabel jLabelNumero17;
    private javax.swing.JLabel jLabelNumero18;
    private javax.swing.JLabel jLabelNumero19;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero20;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelNumero4;
    private javax.swing.JLabel jLabelNumero5;
    private javax.swing.JLabel jLabelNumero6;
    private javax.swing.JLabel jLabelNumero7;
    private javax.swing.JLabel jLabelNumero8;
    private javax.swing.JLabel jLabelNumero9;
    private javax.swing.JLabel jLabelPC;
    private javax.swing.JLabel jLabelPC1;
    private javax.swing.JLabel jLabelPC10;
    private javax.swing.JLabel jLabelPC11;
    private javax.swing.JLabel jLabelPC12;
    private javax.swing.JLabel jLabelPC13;
    private javax.swing.JLabel jLabelPC14;
    private javax.swing.JLabel jLabelPC15;
    private javax.swing.JLabel jLabelPC16;
    private javax.swing.JLabel jLabelPC17;
    private javax.swing.JLabel jLabelPC18;
    private javax.swing.JLabel jLabelPC19;
    private javax.swing.JLabel jLabelPC2;
    private javax.swing.JLabel jLabelPC20;
    private javax.swing.JLabel jLabelPC3;
    private javax.swing.JLabel jLabelPC4;
    private javax.swing.JLabel jLabelPC5;
    private javax.swing.JLabel jLabelPC6;
    private javax.swing.JLabel jLabelPC7;
    private javax.swing.JLabel jLabelPC8;
    private javax.swing.JLabel jLabelPC9;
    private javax.swing.JLabel jLabelPCElegida;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jTextFieldHoras;
    // End of variables declaration//GEN-END:variables
}
