/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionAdmin;

/**
 *
 * @author LABCISCO-PC059
 */
public class JframeAdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form JframeElegirSoftware
     */
    public JframeAdminMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelLogoItson = new javax.swing.JLabel();
        jButtonAdminEquipos = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonGenerarReportes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFunciones = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFunciones1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 400));

        jPanelFondo.setBackground(new java.awt.Color(153, 204, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoItson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelFondo.add(jLabelLogoItson, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 177, 100));

        jButtonAdminEquipos.setBackground(new java.awt.Color(0, 102, 255));
        jButtonAdminEquipos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdminEquipos.setText("Admninistracion De Equipo");
        jButtonAdminEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminEquiposActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonAdminEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 214, -1));

        jButtonVolver.setBackground(new java.awt.Color(0, 102, 255));
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 90, -1));

        jButtonGenerarReportes.setBackground(new java.awt.Color(0, 102, 255));
        jButtonGenerarReportes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerarReportes.setText("Generar Reportes");
        jButtonGenerarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarReportesActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonGenerarReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 214, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 0));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Instituto Tecnologico de Sonora");
        jPanelFondo.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 60));

        jLabelFunciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFunciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFunciones.setText("Menu Administrador");
        jPanelFondo.add(jLabelFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 210, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 10));

        jLabelFunciones1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFunciones1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFunciones1.setText("Funciones");
        jPanelFondo.add(jLabelFunciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        JframeAdminIngreso j = new JframeAdminIngreso();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAdminEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminEquiposActionPerformed
        JframeAdminEquipos j = new JframeAdminEquipos();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAdminEquiposActionPerformed

    private void jButtonGenerarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarReportesActionPerformed
        JframeAdminReportes j = new JframeAdminReportes();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGenerarReportesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdminEquipos;
    private javax.swing.JButton jButtonGenerarReportes;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelFunciones;
    private javax.swing.JLabel jLabelFunciones1;
    private javax.swing.JLabel jLabelLogoItson;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
