/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionAdmin;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author LABCISCO-PC059
 */
public class JframeAdminReporteCarreraFiltro extends javax.swing.JFrame {

    private String filtrosAux = "";
    private List<String> CarrerasAux = new ArrayList<>(); //Auxiliar para guardar filtros.
    private String aux1;
    private Date fechaInicioAux;
    private Date fechaFinAux;

    /**
     * Creates new form JframeElegirSoftware
     */
    public JframeAdminReporteCarreraFiltro() {
        initComponents();
        this.setLocationRelativeTo(null);
        CarrerasAux = new ArrayList<>(this.jComboBoxCarreras.getItemCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelLogoItson = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFiltros1 = new javax.swing.JLabel();
        jLabelCarreras = new javax.swing.JLabel();
        jComboBoxCarreras = new javax.swing.JComboBox<>();
        jLabelHorario = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelFechaFin = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jTextFieldFechaFin = new javax.swing.JTextField();
        jLabeFiltroSeleccionado2 = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAñadirCarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(759, 450));

        jPanelFondo.setBackground(new java.awt.Color(153, 204, 255));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoItson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoItson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LogoITSON.png"))); // NOI18N
        jPanelFondo.add(jLabelLogoItson, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 177, 100));

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 322, 81, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 10));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Instituto Tecnologico de Sonora");
        jPanelFondo.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 50));

        jLabelFiltros1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFiltros1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFiltros1.setText("Selección de Filtros");
        jPanelFondo.add(jLabelFiltros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 220, -1));

        jLabelCarreras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCarreras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarreras.setText("Carreras");
        jPanelFondo.add(jLabelCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 126, 17));

        jComboBoxCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C 1", "C 2", "C 3", "C 4", " " }));
        jComboBoxCarreras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCarrerasItemStateChanged(evt);
            }
        });
        jComboBoxCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCarrerasActionPerformed(evt);
            }
        });
        jPanelFondo.add(jComboBoxCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabelHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHorario.setText("Horario");
        jPanelFondo.add(jLabelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 126, 17));

        jLabelFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaInicio.setText("Fecha Inicio");
        jPanelFondo.add(jLabelFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 81, 17));

        jLabelFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFechaFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaFin.setText("Fecha Fin");
        jPanelFondo.add(jLabelFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 81, 17));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 293, 81, -1));
        jPanelFondo.add(jTextFieldFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 81, -1));
        jPanelFondo.add(jTextFieldFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 81, -1));

        jLabeFiltroSeleccionado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeFiltroSeleccionado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFondo.add(jLabeFiltroSeleccionado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 100, 71));

        jButtonLimpiar.setText("Restablecer Filtro");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jButtonAñadirCarrera.setText("Añadir Filtro");
        jButtonAñadirCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirCarreraActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonAñadirCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        JframeAdminMenu j = new JframeAdminMenu();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jComboBoxCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCarrerasActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed

        if (this.CarrerasAux.isEmpty()) {
            for (int i = 0; i < this.jComboBoxCarreras.getItemCount(); i++) {
                this.CarrerasAux.add(this.jComboBoxCarreras.getItemAt(i));
            }
        }
        try {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            this.fechaInicioAux = formato.parse(this.jTextFieldFechaInicio.getText());
            this.fechaFinAux = formato.parse(this.jTextFieldFechaFin.getText());
            JframeAdminReporteCarreraConfirmacion j = new JframeAdminReporteCarreraConfirmacion(this.CarrerasAux, this.fechaInicioAux, this.fechaFinAux);
            j.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Valores no validos en Fechas");
        }


    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboBoxCarrerasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCarrerasItemStateChanged

    }//GEN-LAST:event_jComboBoxCarrerasItemStateChanged

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        List<String> vacio = new ArrayList<>(); //Auxiliar vacio.
        CarrerasAux = vacio; // Igualación para que el auxiliar de Carreras vuelva a estar vacio.
        this.jLabeFiltroSeleccionado2.setText(" ");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAñadirCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirCarreraActionPerformed
        boolean aux2 = false; //Auxiliar para saber si el valor ya existe en la lista de carreras, false si no existe, true si si existe.
        for (int i = 0; i < CarrerasAux.size(); i++) {
            //If que comprueba si la carrera de la combobox ya existe en la lista o no.
            if (CarrerasAux.get(i).equalsIgnoreCase(this.jComboBoxCarreras.getItemAt(this.jComboBoxCarreras.getSelectedIndex()))) {
                aux2 = true;
            }
        }
        //Si el auxiliar utilizado es false, entonces el valor de la combobox no existe aun en la lista, por lo cual es seguro añadirlo al filtro.
        if (aux2 == false) {
            this.CarrerasAux.add(this.jComboBoxCarreras.getItemAt(this.jComboBoxCarreras.getSelectedIndex()));
            this.jLabeFiltroSeleccionado2.setText(this.CarrerasAux.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Carrera ya añadida al filtro.");
        }
    }//GEN-LAST:event_jButtonAñadirCarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAñadirCarrera;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxCarreras;
    private javax.swing.JLabel jLabeFiltroSeleccionado2;
    private javax.swing.JLabel jLabelCarreras;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelFiltros1;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelLogoItson;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jTextFieldFechaFin;
    private javax.swing.JTextField jTextFieldFechaInicio;
    // End of variables declaration//GEN-END:variables
}
